yarnPath: .yarn/releases/yarn-3.2.1.cjs

nodeLinker: node-modules

checksumBehavior: throw

npmScopes:
  myhill-cycling:
    npmRegistryServer: "https://npm.pkg.github.com"

packageExtensions:
  "@astrojs/svelte-language-integration@*":
    dependencies:
      typescript: "*"
  "@commitlint/cz-commitlint@*":
    dependencies:
      inquirer: "^8"
