name: Delete Environment

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
    secrets:
      APPLICATION_ID:
        required: true
      APPLICATION_PRIVATE_KEY:
        required: true

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v1
        with:
          organization: "myHill-Cycling"
          permissions: "contents:read,checks:read,deployments:write,org:write"
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}

      - uses: strumwolf/delete-deployment-environment@v2
        with:
          # ⚠️ The provided token needs permission for admin write:org
          token: ${{ steps.get_workflow_token.outputs.token }}
          environment: ${{ inputs.environment }}