on:
  workflow_call:
    inputs:
      WebsiteUrl:
        description: "The url of the website to audit"
        type: string
        required: true

jobs:
  scan_links:
    if: ${{ inputs.WebsiteArtifactName == '' }}
    runs-on: ubuntu-latest
    name: 🔍 Scan website for broken links
    steps:
      - uses: ScholliYT/Broken-Links-Crawler-Action@v3
        name: 🕷️ Crawl links
        with:
          website_url: ${{ inputs.WebsiteUrl }}
          exclude_url_prefix: "https://fonts.gstatic.com,https://fonts.googleapis.com"
          exclude_url_suffix: "/about,/policy/privacy,/policy/toc,/hillclimb,/services,/shop,/gateway2racing"
          verbose: true
          max_retry_time: 30
          max_retries: 5
          max_depth: -1
