on:
  workflow_dispatch:
  schedule:
    - cron: "0 15 */2 * *"

jobs:
  audit_http:
    uses: ./.github/workflows/http_audit.yml
    with:
      WebsiteUrl: https://calm-plant-0e1398703.1.azurestaticapps.net

  scan_links:
    uses: ./.github/workflows/link_scanner.yml
    with:
      WebsiteUrl: https://calm-plant-0e1398703.1.azurestaticapps.net/

  run_lighthouse:
    uses: ./.github/workflows/lighthouse_audit.yml
    secrets:
      LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
    with:
      Url: "https://calm-plant-0e1398703.1.azurestaticapps.net"