name: Pull request checks
on: 
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
    paths-ignore:
      - "**/CHANGELOG.md"

jobs:
  build_website:
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    uses: ./.github/workflows/build_artifact.yml

  lighthouse:
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    uses: ./.github/workflows/lighthouse_audit.yml
    needs: [build_website]
    secrets:
      LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
    with:
      Url: "http://localhost:3000/"
      WebsiteArtifactName: ${{ needs.build_website.outputs.WebsiteArtifactName }}

  cypress_test:
    permissions: write-all
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    uses: ./.github/workflows/cypress_tests.yml
    needs: [build_website]
    with:
      WebsiteArtifactName: ${{ needs.build_website.outputs.WebsiteArtifactName }}
    secrets:
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

  deploy_preview:
    environment:
      name: pr-${{github.event.number}}
      url: ${{ steps.deploy.outputs.static_web_app_url }}
    needs: [build_website, cypress_test, lighthouse]
    permissions:
      checks: write
      contents: read
      deployments: write
      issues: write
      pull-requests: write
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    runs-on: ubuntu-latest
    name: Deploy preview app
    outputs:
      static_web_app_url: ${{ steps.deploy.outputs.static_web_app_url }}
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.build_website.outputs.WebsiteArtifactName }}
          # download all files into "dist" folder
          path: dist

      - name: Deploy Release
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          skip_deploy_on_missing_secrets: ${{ env.ACT }} # Skip when running locally
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "./dist" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "" # Built app content directory - optional
          skip_app_build: true
          ###### End of Repository/Build Configurations ######
  
  audit_http:
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    uses: ./.github/workflows/http_audit.yml
    needs: [deploy_preview]
    with:
      WebsiteUrl: ${{ needs.deploy_preview.outputs.static_web_app_url }}

  # scan_links_live:
  #   if: github.event_name == 'pull_request' && github.event.action != 'closed'
  #   uses: ./.github/workflows/link_scanner.yml
  #   needs: [deploy_preview]
  #   with:
  #     WebsiteUrl: ${{ needs.deploy_preview.outputs.static_web_app_url }}
  
  close_pull_request_preview:
    permissions:
      checks: write
      contents: read
      deployments: write
      issues: write
      pull-requests: write
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Preview
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"

  delete_deployments:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    uses: ./.github/workflows/delete_env.yml
    with:
      environment: pr-${{github.event.number}}
    secrets:
      APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
      APPLICATION_PRIVATE_KEY: ${{ secrets.APPLICATION_PRIVATE_KEY }}