name: Pull request checks
on: 
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
    paths-ignore:
      - "**/CHANGELOG.md"

jobs: 
  build_website:
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    uses: ./.github/workflows/build_artifact.yml  

  deploy_preview:
    environment:
      name: pr-${{github.event.number}}
      url: ${{ steps.deploy.outputs.static_web_app_url }}
    needs: [build_website]
    permissions:
      checks: write
      contents: read
      deployments: write
      issues: write
      pull-requests: write
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    runs-on: ubuntu-latest
    name: 🚀 Deploy preview app
    outputs:
      static_web_app_url: ${{ steps.deploy.outputs.static_web_app_url }}
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v3
        with:
          lfs: false

      - name: 📦 Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.build_website.outputs.WebsiteArtifactName }}
          # download all files into "dist" folder
          path: dist

      - name: 🚀 Deploy Release
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        env:
          CUSTOM_BUILD_COMMAND: "yarn add --cached"
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "./dist" # App source code path
          api_location: "./api" # Api source code path - optional
          api_build_command: "yarn workspace @myhill-cycling/astra-web.api build"
          output_location: "" # Built app content directory - optional
          skip_app_build: true
          ###### End of Repository/Build Configurations ######
  
  lighthouse:
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    uses: ./.github/workflows/lighthouse_audit.yml
    needs: [deploy_preview]
    secrets:
      LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
    with:
      Url: ${{ needs.deploy_preview.outputs.static_web_app_url }}

  test:
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    uses: ./.github/workflows/tests.yml
    needs: [deploy_preview]
    with:
      DeploymentUrl: ${{ needs.deploy_preview.outputs.static_web_app_url }}

  audit_http:
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    uses: ./.github/workflows/http_audit.yml
    needs: [deploy_preview]
    with:
      WebsiteUrl: ${{ needs.deploy_preview.outputs.static_web_app_url }}

  # scan_links_live:
  #   if: github.event_name == 'pull_request' && github.event.action != 'closed'
  #   uses: ./.github/workflows/link_scanner.yml
  #   needs: [deploy_preview]
  #   with:
  #     WebsiteUrl: ${{ needs.deploy_preview.outputs.static_web_app_url }}
  
  close_pull_request_preview:
    permissions:
      checks: write
      contents: read
      deployments: write
      issues: write
      pull-requests: write
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: 📪 Close Preview Enviroment
    steps:
      - name: ☁️ Shutdown azure enviroment
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"

      - name: 🌲 Delete GitHub Enviroment
        uses: bobheadxi/deployments@v1
        with:
          step: delete-env
          token: ${{ secrets.GITHUB_TOKEN }}
          env: pr-${{github.event.number}}
          desc: Environment was deleted as part of closing a pull request preview
